<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtVvC33\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtVvC33/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPtVvC33.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPtVvC33\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPtVvC33\App_KernelTestDebugContainer([
    'container.build_hash' => 'PtVvC33',
    'container.build_id' => '162e31e4',
    'container.build_time' => 1690499630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtVvC33');
