<?php

namespace ContainerDftrAv3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2_R_ZSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._2.R.ZS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._2.R.ZS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produtoRepository' => ['privates', 'App\\Repository\\ProdutoRepository', 'getProdutoRepositoryService', true],
        ], [
            'produtoRepository' => 'App\\Repository\\ProdutoRepository',
        ]);
    }
}
