<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDftrAv3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDftrAv3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDftrAv3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDftrAv3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDftrAv3\App_KernelDevDebugContainer([
    'container.build_hash' => 'DftrAv3',
    'container.build_id' => '4666923b',
    'container.build_time' => 1690693301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDftrAv3');
