<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'register_app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_bootstrap_dist_js_bootstrap_esm_js-node_modules_jquery_dist_jquery_js.js',
                '/build/register_app.js',
            ],
            'css' => [
                '/build/register_app.css',
            ],
        ],
        'global_app' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'login_app' => [
            'js' => [
                '/build/runtime.js',
                '/build/login_app.js',
            ],
            'css' => [
                '/build/login_app.css',
            ],
        ],
    ],
],

]];
