<?php

namespace ContainerRFr1wHR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduto2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Rhy.U4w.App\Entity\Produto' shared service.
     *
     * @return \App\Entity\Produto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Rhy.U4w": it needs an instance of "App\\Entity\\Produto" but this type has been excluded in "config/services.yaml".');
    }
}
